name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 2-11 * * 1-5"  # update every work hours on weekdays (10AM - 7PM in GMT+8)
    - cron: "0 16 * * *"      # update every night                  
  push:
    branches: 
      - master
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 06296b427610b004e9373363a8360afc
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
